title: Dana Amundsen #Website Name
logo: # /assets/img/logo.png
favicon: #eg. /assets/img/favicon.png
description: Graphic Designer and Visual Storyteller #Website Description
google_analytics: 
theme: jekyll-theme-minimal
excerpt_separator: <!--more-->
paginate: 5 #Posts per page
paginate_path: "/page:num/"
plugins: 
  - jekyll-paginate
  - jekyll-feed
  
# style
google_fonts: Yes #yes or no
body_font: Old Standard TT #Cormorant Garamond #font used for body text
header_font: Schibsted Grotesk #font used for title and headers
background_color: "#F0EEE9"
font_color: "#28282D"
color1: "#6667AB" #color of links and headers
color2: "#615C61" #color of links on hover
layout: single_column #single_column option

# social media (full urls)
instagram: http://www.instagram.com/danaamundsen
facebook: 
tumblr: 
youtube: 
mastodon: http://illo.social/@danaamundsen
kofi: 
patreon: 
twitch: 
